[project]
authors = ["Rüdiger W. Braun <Ruediger.Braun@hhu.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mfb2425"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.2.3,<3"
notebook = "<7"
scipy = ">=1.14.1,<2"
statsmodels = ">=0.14.3,<0.15"
seaborn = ">=0.13.2,<0.14"
openpyxl = ">=3.1.5,<4"
rise = ">=5.7.1,<6"
